### ISSUE TITLE
Create the "Download as Sprite" Button and put it in the Prompt Image Window

### ISSUE THREAD

**Issue by Morgan-6Freedom** [scenario-labs/Scenario-Unity#114]
```[tasklist]
### Tasks
- [x] When user clicks on this button, change the modal to display the settings of this feature
- [x] Implement a default sprite importer preset
- [x] Let the user be able to choose a specific sprite importer preset
- [x] Specify to the user that the background will be removed by default (user can change)
- [x] Make a boolean "always remove backgroud for sprites"
- [x] Make a boolean in the settings "use Pixels per Units equal to image width"
- [x] Change the PIxels per Unit to the value of the image width if the settings is ON
```
