### ISSUE TITLE
Improve the Prompt Image Window Modal

### ISSUE THREAD

**Issue by Morgan-6Freedom** [scenario-labs/Scenario-Unity#115]
```[tasklist]
### Tasks
- [x] Put all the buttons in a vertical way
- [x] Change "Refine image" wording to "Set image as a reference"
- [x] Refine Image (Set Image as Reference) button should warn the user that the Prompt Window has been updated
- [x] Refine Image (Set Image as Reference) button should opens the Prompt Window
- [x] Refine Image (Set Image as Reference) button should switch Prompt Window from Text to Image or Inpainting to Image to Image
- [x] "Download" button should be "Download as Texture"
- [x] The modal should not close when the user clicks on another window. Instead put a close button
- [x] Make the button list scrollable
- [x] Download as Texture warns the user what happened when they click on it.
- [x] Delete warns the user what happened when they click on it
- [x] Remove Backgorund warn the user what happened when they click on it
```

**Comment by Morgan-6Freedom** [comment]
all vertical.
No horizontal & vertical buttons

![Image](https://github.com/scenario-labs/Scenario-Unity/assets/49686866/7f39f591-084d-43f3-8a0d-31d4459aaee8)

**Comment by Morgan-6Freedom** [comment]
This is how it looks like now

https://github.com/scenario-labs/Scenario-Unity/assets/49686866/32f195ab-ad76-47d9-8a88-6d275ddeb1f9
