### ISSUE TITLE
Improve the "download" button to "Download as Texture" Button and put it in the Prompt Image Window

### ISSUE THREAD

**Issue by Morgan-6Freedom** [scenario-labs/Scenario-Unity#116]
```[tasklist]
### Tasks
- [x] Implement a default texture importer preset
- [x] Let the user be able to choose a specific texture importer preset
- [x] Change the settings page to let the user change the default texture importer preset
- [x] Use the preset when download the images as texture
```

**Comment by Morgan-6Freedom** [comment]
https://www.loom.com/share/fd269cb5aced464a974ab5f12eb536c9?sid=7625ec1e-c7b4-4dfc-bece-962164c54cc7
