### ISSUE TITLE
Create the "Download as Tile" Button and put it in the Prompt Image Window

### ISSUE THREAD

**Issue by Morgan-6Freedom** [scenario-labs/Scenario-Unity#117]
```[tasklist]
### Tasks
- [x] When user clicks on this button, change the modal to display the settings of this feature
- [x] Implement a default sprite importer preset for isometric tiles
- [x] Implement a default sprite importer preset for rectangular tiles
- [x] Let the user be able to choose a specific sprite importer preset
- [x] Specify to the user that the background will be removed by default (user can change)
- [x] Ask the user to reference a Tile Palette Asset
- [x] Automatically change the Cell Layout according to the Tile Palette Asst
- [x] Have a warning message if the user choose a Cell layout that doesn't match their TilePalette Settings
- [x] Have a validate button (that works only if tilepalette asset is referenced)
- [x] When the user validate, remove backgound (or not) + download image + set the sprite preset + create a tile asset + add the tile asset to the tile palette
- [x] Have a cancel button in the modal to revert
- [x] Warn the user we only support Isometric & Rectangle for now
```

**Comment by Morgan-6Freedom** [comment]
https://www.loom.com/share/ad25af2939aa40fabcac09ca1537fb9c
