### ISSUE TITLE
Merge the prompt Image window and the Images Window

### ISSUE THREAD

**Issue by Morgan-6Freedom** [scenario-labs/Scenario-Unity#135]
```[tasklist]
### Tasks
- [x] Make the Images window with a scrollview (like the Prompt Image window)
- [x] Put the newly generated images in the images window instead of the prompt images window
- [x] Put all the changes of the selected image model from the Prompt Images window inside the Images window
- [x] Remove the prompt image window
```

**Comment by Morgan-6Freedom** [comment]
https://www.loom.com/share/0371fb0089b743cd99e8e9929a19ee7c?sid=c17785fd-505d-4ac4-90b6-e08b4c95cc61
